### ISSUE TITLE
Crash to desktop - Flight simulator 2020

### ISSUE THREAD

**Issue by yushiromarcel** [mbucchia/VirtualDesktop-OpenXR#10]
Flight simulator 2020  crash to desktop when I switch to VR

**Environment**

- _Application/Game and version_: FS2020 1.34.16.0
- _Version of Virtual Desktop_:  VDXR 1.29.3

1. Run flight simulator
2 . switch to VR
3. crash to desktop FS2020.

Strange thing : I use PICO 4 Headset but in the log file it is Oculus Rift S (16)...

**Comment by mbucchia** [comment]
Try these instructions 
https://forums.flightsimulator.com/t/virtual-desktop-native-openxr-support-is-here/613733/61

**Comment by yushiromarcel** [comment]
Yes works fine. Thanks !
