### ISSUE TITLE
Python error while compiling openxr 

### ISSUE THREAD

**Issue by yushiromarcel** [mbucchia/VirtualDesktop-OpenXR#11]
Hi, I'm trying to compile openXR but I've this error in visual studio :  'dispatch_generator.py'

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3073	The command "python C:\Users\yushi\Documents\Projets\simulateur\En cours\Openxr\OpenXR-MotionCompensation\XR_APILAYER_NOVENDOR_motion_compensation\\framework\dispatch_generator.py
:VCEnd" exited with code 2.	XR_APILAYER_NOVENDOR_motion_compensation	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets	150	

I've checked path to open XR SDK souce, mixed reality and SDK and seems OK. 
Python is correctly installed. 

any idea what's wrong ?

Thanks !

**Comment by mbucchia** [comment]
Your log shows you are trying to compile OpenXR-MotionCompensation. Did you file this issue in the wrong GitHub??

**Comment by yushiromarcel** [comment]
Hi, I solved this issue by suppression the whitespace int the path of the folder ('En_cours'). 
But now I've a second issue when executing the python script : 
It's a Type 1 error. Seems an issue line 402 of the python script : 
registry.apiGen(AutomaticSourceGeneratorOptions(
        conventions       = conventions,
        filename          = 'dispatch.gen.cpp',
        directory         = cur_dir,
        apiname           = 'openxr',
        profile           = None,
        versions          = featuresPat,
        emitversions      = featuresPat,
        defaultExtensions = 'openxr',
        addExtensions     = None,
        removeExtensions  = None,
        emitExtensions    = extensionsPat))

Any idea ?
Could be a issue with my SDK version ?

![2023-11-07 10_07_01-OpenXR-MotionCompensation - Microsoft Visual Studio](https://github.com/mbucchia/VirtualDesktop-OpenXR/assets/7780082/b5a0bc48-4044-4c4b-98e5-9e16b1cc170e)

**Comment by mbucchia** [comment]
Clearly not a VDXR issue (you are literally trying to compile a different project).

Closing.
