### ISSUE TITLE
Access the menu to change resolution

### ISSUE THREAD

**Issue by felipe-ff** [mbucchia/VirtualDesktop-OpenXR#15]
Hi, I saw an youtube video where the person could access a menu to change various configurations, including setting a custom resolution, how could I access this menu?

**Comment by mbucchia** [comment]
It's a different tool: https://mbucchia.github.io/OpenXR-Toolkit/

But I don't recommend that you change the resolution there, just use the Virtual Desktop quality settings to control resolution.
