### ISSUE TITLE
Virtual Desktop hangs after exit VR Mode on X-Plane 12

### ISSUE THREAD

**Issue by Roccote** [mbucchia/VirtualDesktop-OpenXR#16]
**ANY ISSUE FILED WITHOUT THE INFORMATION REQUIRED BELOW WILL BE CLOSED WITHOUT BEING LOOKED AT. NO EXCEPTIONS.**

When trying to exit VR mode in X-Plane12 (--open_xr and Quest 3) the app hangs 
and when trying to enter VR mode again in XP12 after resetting both Quest 3 and PC apps the image turns into a quick slideshow of turning view images

**Environment**

- _Application/Game and version_: X-plane 12 with --open_xr flag, Quest 3 headset, VDXR runtime
- _Version of Virtual Desktop_: 1.29.9

**To Reproduce**

1.- Start X-Plane 12 in OpenXR Mode using --open_xr flag
2.- Start a flight, once in the cockpit go to settings>VR hardware>Enable VR hardware (thick checkbox)
3.-Once in VR mode select "Disable VR headset" on 2D window on X-plane12 window on PC or go to "settings>VR hardware>Enable VR hardware (unthick checkbox)
4.-VD hangs on headset (image freezes), only viable option is quitting VD app with right controller oculus button
5.- Restarting Quest3 VD app and trying to activate VR mode again on XP12 results in the previously mentioned quick slideshow of turning view images

**Expected behavior**

after selecting "disable VR hardware" on X-plane 12, the view in the Quest 3 headset should return to the VD app and one should be able to re-enter VR mode in X-plane 12 again

[OpenXR.log.txt](https://github.com/mbucchia/VirtualDesktop-OpenXR/files/13483919/OpenXR.log.txt)

**Comment by mbucchia** [comment]
You seem to have OpenXR Toolkit enabled, which isn't compatible with this game.

X-Plane is working fine for me without it, I tried switching VR mode several times without issues.

**Comment by Roccote** [comment]
I had installed the nightly build OXRTK compatible with XP12 I only used it to display the framerate, anyway after your comment I first deactivated and then uninstalled it. Now I can return to VR mode in X-Plane but the image is very unstable (lots of movement) and then after a while it stabilizes by itself. I tried three times, first one stabilized in about 10 seconds, second time in about 30 and third took almost two minutes, here´s a video of the third time: https://www.youtube.com/watch?v=GTFMale5FGE. Btw, I have a joystick button assigned to enable/disable VR Mode in XP12 and that is what I used to switch modes. Now I´m tot sure what is wrong but another member of xplane.org forum has exactly the same symptoms.
[OpenXR.log.txt](https://github.com/mbucchia/VirtualDesktop-OpenXR/files/13485193/OpenXR.log.txt)

**Comment by mbucchia** [comment]
Thanks, I think I see the issue now. Don't know when I will have time to fix it though.

**Comment by Roccote** [comment]
Nevermind, we will wait patiently for the fix. Thank you for the support and your continued effort.
________________________________

**Comment by mbucchia** [comment]
I actually think I have a fix, but I need to do more testing (and test with other applications too). What X-Plane is doing with VR session restart is very unusual.

**Comment by mbucchia** [comment]
Fixed by 7c74226.
