### ISSUE TITLE
Feature Request: Height Offset

### ISSUE THREAD

**Issue by jasonridesabike** [mbucchia/VirtualDesktop-OpenXR#18]
_Give us as much details as possible_

VDXR is fantastic and runs so much better than SteamVR, but one of the key advantages SteamVR still has is the ability to offset height using OVR Toolkit. This allows for disabled people as well as anyone who wants to play seated to enjoy VR.

Would it be possible to add configurable height offset as a feature?

**Comment by jasonridesabike** [comment]
I had no idea that was possible haha, will give it a shot. Thanks again! This is the second time you've helped me out with stuff

**Comment by mbucchia** [comment]
Cool! Please let me know if this does what you intend. Perhaps we're not understanding the same request!

**Comment by jasonridesabike** [comment]
I believe we're talking about different things or I'm misunderstanding - I attempted to recenter with stage tracking off and the results are the same.

So with OVR toolkit on SteamVR you're able to set arbitrary x, y, and z offsets in cm that apply to the HMD. So if I'm seated, I can add 50cm of height and voila, "standing" in VR. It's the universal accessibility and laziness solution for those of us wanting to play seated.

In this case I tried the recenter with stage tracking off solution, but when I went in game (Fallout 4 VR in this case) I was still only a meter off the ground while seated IRL. I'm the tiniest wasteland warrior that ever was.

Does that make sense?

**Comment by mbucchia** [comment]
Oh you want to play a standing game while seated and still show at the standing height.

That's a bit odd IMO (in terms of motion sickness, but I understand it's not always a choice).

I can't think of a good solution atm (short of holding your headset high up in the air while recentering).

Adding an option to offset the height is possible. Right now it's gated by the need for a pop-up menu, which I need to work on first. Once I have a pop-up menu, this type of user options will be easy to add.

So for short: agree, will do, but will take time.

**Comment by jasonridesabike** [comment]
Oh I hadn't considered motion sickness, I'm one of those fortunate few unaffected.

Holding up and recentering unfortunately doesn't work as the distance to ground is what's seemingly used to calculate height. Begs the question if a ground offset might not be easier.

For the moment I've cobbled together workarounds using mods :)

Thanks! Awesome to hear!

**Comment by mbucchia** [comment]
What game is it that you've been trying btw?

**Comment by jasonridesabike** [comment]
Fallout 4 VR. An excellent candidate for seated standing given how many hours upon hours you can sink in. Using FRIK to modify camera height, although my arms are all flayed out and weird now. There should be a way to fix that with some ini edits so experimenting with those.

**Comment by jasonridesabike** [comment]
News on this! Someone on Reddit pointed out to me that there's an "add height" feature in the Quest accessibility settings. It's boolean and adds a fixed amount of height, so still not as nice as having fine tuned control but it does the trick in a pinch. I'm still about a half foot shorter than I am in real life, but I can live with this new perspective haha.

In caase anyone stumbles onto this in the future.

**Comment by mbucchia** [comment]
This feature is in a branch now, but I am not sure yet whether it will be released. Closing.
