### ISSUE TITLE
Problem running Resist

### ISSUE THREAD

**Issue by vkhromenkov** [mbucchia/VirtualDesktop-OpenXR#19]
**ANY ISSUE FILED WITHOUT THE INFORMATION REQUIRED BELOW WILL BE CLOSED WITHOUT BEING LOOKED AT. NO EXCEPTIONS.**

**Describe the bug**

Black vr space after starting the game.
Nothing happens.

[OpenXR.log](https://github.com/mbucchia/VirtualDesktop-OpenXR/files/13626118/OpenXR.log)
[Log from the game](https://github.com/mbucchia/VirtualDesktop-OpenXR/files/13626140/Player.log)

**Environment**

- _Application/Game and version_: Resist v1.0.2.023
- _Version of Virtual Desktop_: 1.29.10

**To Reproduce**

_Steps to reproduce the behavior:_

1. Run 'Resist' game from VD Games tab with OpenXR Runtime set to VDXR

**Expected behavior**

Game started, dev/publisher logos displayed and title menu is shown

**Comment by mbucchia** [comment]
This should be fixed by a2b1c16 already, but this fix won't be published until the next release of Virtual Desktop.

**Comment by mbucchia** [comment]
I just bought the game this morning and confirmed that it is fixed.

**Comment by rom1usa** [comment]
Which 'game' ?

**Comment by mbucchia** [comment]
The game this GitHub thread is titled after

![image](https://github.com/mbucchia/VirtualDesktop-OpenXR/assets/69611560/2324edee-bdc6-4914-bf4b-6c5e88ce6fe5)

**Comment by vkhromenkov** [comment]
Is this available in latest VD - 1.30.0 ?
Still having black screen

**Comment by vkhromenkov** [comment]
> This should be fixed by [a2b1c16](https://github.com/mbucchia/VirtualDesktop-OpenXR/commit/a2b1c16c15221abe565492092fd7a6df19c7c00d) already, but this fix won't be published until the next release of Virtual Desktop.

Is this available in latest VD - 1.30.0 ?
Still having black screen

**Comment by mbucchia** [comment]
I have just tested it with the official release, working fine.

**Comment by vkhromenkov** [comment]
Checked it again - it runs fine from Steam (Oculus VR mode), but not from Games tab in VD.
In other words:
- Run from Steam in Steam VR mode: fine, runtime = SteamVR
- Run from Steam in Steam VR mode: fine, runtime = VDXR
- Run from VD Games tab, runtime = VDXR: not working, just black void
- Run from VD Games tab, runtime = Automatic: fine, runtime = SteamVR

**Comment by vkhromenkov** [comment]
> I have just tested it with the official release, working fine.

So, should I reopen this bug or is it on the VD side and I should notify VD devs?
