### ISSUE TITLE
Report: The Last Clockwinder runs with VDXR

### ISSUE THREAD

**Issue by vkhromenkov** [mbucchia/VirtualDesktop-OpenXR#20]
Don't see this game in the list.

Game: The Last Clockwinder
Distribution: Steam
OpenXR Runtime in VD: VDXR
Runtime in overlay: VDXR

Started the game from Games tab in VD and played for about half an hour - didn't find any problems.

**Comment by mbucchia** [comment]
Thank you, added to the list!
