### ISSUE TITLE
Seeking the best hardware for wireless Virtual Desktop XR and Quest 3

### ISSUE THREAD

**Issue by lk251** [mbucchia/VirtualDesktop-OpenXR#24]
Could you please advise on the optimal hardware for achieving the fastest wireless connection between a PC and the Meta Quest 3? Specifically, does Wireless Virtual Desktop XR support the D-Link VR Air Bridge, or is there another Wi-Fi 6 device you'd recommend for this purpose?

Thank you for this amazing software! 

GPU RTX 4090
RAM 64
CPU 13600KF

**Comment by mbucchia** [comment]
Please use the Virtual Desktop Discord for this type of question. 

https://discord.com/invite/weZcTXtT
