### ISSUE TITLE
Triggers require a lot of pressure to activate in some games

### ISSUE THREAD

**Issue by Sl0vi** [mbucchia/VirtualDesktop-OpenXR#26]
**Describe the bug**

I'm currently experiencing this issue in Phasmophobia and Lethal Company with the LethalCompanyVR mod.

When interacting with menus, the journal in Phasmophobia and the terminal in Lethal Company, I have to put a lot of pressure on the triggers in order for the items to activate. It feels like VDXR wants me to press the triggers further than 100% at times.

This issue also isn't consistent, it seems to get worse the longer I play the games. Usually when I first start up the game, the triggers work fine but after a few minutes of play the amount of pressure on the triggers required increases drastically.

This same issue does not happen if I switch to SteamVR, and it does not happen with Native Quest 2 games. The triggers work correctly everywhere else.

[OpenXR.log](https://github.com/mbucchia/VirtualDesktop-OpenXR/files/13933237/OpenXR.log)

**Environment**

- Lethal Company v49 with LethalCompanyVR v1.0.1
- Phasmophobia v0.9.4.0
- Virtual Desktop 1.29.10
- Quest 2

**To Reproduce**

1. Run Lethal Company with LethalCompanyVR mod loaded, or Phasmophobia in VR mode
2. Play the game for a while
3. As you are playing you should notice that interacting with menus, the journal in Phasmophobia or the terminal in Lethal Company gets more and more difficult requiring you to put more and more pressure on the triggers for them to activate.

**Expected behavior**

When the triggers are pressed items should activate without having to squeeze the triggers like crazy.

**Comment by mbucchia** [comment]
The threshold value is currently set to 95% of the full trigger: https://github.com/mbucchia/VirtualDesktop-OpenXR/blob/main/virtualdesktop-openxr/action.cpp#L571

I could change the value, but then I will only just have new issues opened because people will find it too sensitive. I'm testing Phasmophobia right now and I'm having no problem, so could it just be that your controllers are worn out?

Let me try to find out what threshold SteamVR uses.

**Comment by mbucchia** [comment]
SteamVR uses an insanely low threshold around 20%, while Oculus Link uses somewhere around 50%.

I suppose I can lower the threshold to 50% to mimic Oculus Link.

**Comment by mbucchia** [comment]
Done in 2586779fd09963e22c13bd15a33955086153dd5b, will be released with Virtual Desktop 1.30.0.

**Comment by Sl0vi** [comment]
I suppose there can be some wear on my controllers. My Quest 2 is almost 2 years old and I have used it quite a lot.

Maybe Airlink and SteamVR use lower thresholds in anticipation of that controller triggers will wear down over time?

I've never had any issues with the lower thresholds making the triggers overly sensitive or anything like that, even when my headset was brand new, so I don't know if lowering the threshold causes any issues.

**Comment by Sl0vi** [comment]
Virtual Desktop 1.30.0 just released and the difference this change made is huge.

It was immediately noticeable just how much more responsive the triggers are when interacting with menus with the new threshold. Both Lethal Company and Phasmophobia are perfectly playable now with this change.

Even in other games interacting with menus is much more responsive than it was before.

So far I have not noticed any negative consequences to the new threshold.

**Comment by mbucchia** [comment]
Cool, thanks for reporting back, I'm glad we have better alignment now!
