### ISSUE TITLE
left/right eye only behavior on quad layers

### ISSUE THREAD

**Issue by Xeth84** [mbucchia/VirtualDesktop-OpenXR#28]
I have been using UEVR with VDXR and have been loving it.  There is a "2D mode" on UEVR that will toggle the game out of full VR to a stereoscopic version in theater mode.  On Oculus Link it is stereoscopic while it is a flat, overlapping left and right eye in VD.  I asked Praydog about this and he thinks that "VDXR may not be implementing the left/right eye only behavior for the quad layers"

Is this something that can be implemented?  

There are some games that look better and all the elements show up in "2D mode" currently and not in VR mode, so I switch to Oculus Link for that, which I would prefer not to since VD is a lot better.

**Comment by mbucchia** [comment]
Not going to be supported, this is too significant of an effort for a very uncommon feature only used by 1 app.

**Comment by mbucchia** [comment]
Reopening for further assessment.

**Comment by mbucchia** [comment]
I did take a closer look and prototyped some code, and while this is achievable, the use case is still too uncommon to justify the full effort of releasing then maintaining the new code.
