### ISSUE TITLE
Vampire: The Masquerade - Justice: Right thumbstick movement doesn't register, rendering resolution cannot be changed

### ISSUE THREAD

**Issue by Neon-White** [mbucchia/VirtualDesktop-OpenXR#29]
**Describe the bug**

I am not even sure that this is a VDXR bug since I suspect it might be down to the way the game implements its OpenXR support, but here goes.

When forcing VTMJ to run in OpenXR mode (which can be done by adding the `-hmd=openxr` launch option and enforcing VDXR in the VD Streamer settings), two problems occur:
1. The right thumbstick movement does not register. Thumbstick clicks work. The left thumbstick works both in movement and in clicking. But very specifically, the right stick's movement does not (so practically, it's possible to crouch but not to turn)
2. The game seems to be stuck at 100% render resolution. There is an option to change the scale in the settings menu. The option works when the game is running through SteamVR, but not when running through VDXR. This happens also despite the fact I'm using the Godlike preset, which should use supersampling by default, if I understand correctly (as is also evident by line 15 of the logs attached below)

Please note that without passing the parameter, the game seems to insist on starting with SteamVR, even when the OpenXR Runtime is set to VDXR.

[OpenXR.log](https://github.com/mbucchia/VirtualDesktop-OpenXR/files/14234547/OpenXR.log)

**Environment**

- _Game and version_: Vampire: The Masquerade - Justice, VtmJustice.exe file version is 4.27.2.0, product version is `UE4 Partner Oculus 4.27-CL-0`
- _Version of Virtual Desktop_: 1.30.1

**To Reproduce**

1. In VD Streamer, set `OpenXR Runtime` to `VDXR`
2. Create a shortcut to `VtmJustice.exe` (executable is present in the root of the game's installation directory)
3. Append the launch parameter `-hmd=openxr` under the shortcut's `Target` field
4. Try to turn by moving the right stick left/right

**Expected behavior**
The character should turn left/right when the right stick is moved left/right

**Comment by mbucchia** [comment]
I'll see if I can somehow obtain the game, but I would hold my breath.

If you must use the command line option to force OpenXR support, then it means the game is probably never tested in this configuration by the developer.

Can you try with SteamVR OpenXR (not OpenVR) and see if those issues occur? Aka, set runtime to SteamVR AND pass the command line argument?

**Comment by mbucchia** [comment]
That sounds about right, not much I could do :(
