### ISSUE TITLE
Works fine in VD 1.29.0 !!!

### ISSUE THREAD

**Issue by huliqan** [mbucchia/VirtualDesktop-OpenXR#3]
Thanks a lot!!! I asked Guy for a long time, but I got it from you :) I checked it in all games with OpenXR and it works fine everywhere without steamVR! Pico4 5.8.2 + VD 1.29.0
True, it’s not OpenXR that says in the info panel, but Oculus :)))
![Screenshot_VirtualDesktop Android_2023 10 13-22 39 09 276_204](https://github.com/mbucchia/VirtualDesktop-OpenXR/assets/11330258/417152b7-7cab-4e82-8fae-c1e712016c94)

**Comment by mbucchia** [comment]
Thanks.

No one ever said It didn't work with 1.29.0 though.

**Comment by huliqan** [comment]
I thought we needed beta 1.29.1 :)
