### ISSUE TITLE
Paradiddle compatibility

### ISSUE THREAD

**Issue by Lordubuntu94** [mbucchia/VirtualDesktop-OpenXR#31]
The following game can be added to the compatibility list:

Game: Paradiddle
Distribution: Steam
OpenXR Runtime in VD: VDXR
Runtime in overlay: VDXR

to use openXR the additional parameter "-hmd=openxr" is needed.
Game runs fine, the only hair in the soup is the default drum sticks position. The standard offset is wrong, but luckly in game there's a slider that can fix this as workaround.

**Comment by mbucchia** [comment]
Thanks, I updated the wiki. For the controller offset, it's not surprising for games no intended to be run with OpenXR (the need for the command line argument). If you want, we can add a quirk with correct offsets.

Here's a tool that lets you adjust offsets in real-time.

[OffsetsTool.zip](https://github.com/mbucchia/VirtualDesktop-OpenXR/files/14277101/OffsetsTool.zip)

Typically, doing Grip Pose, Translation, Z=-100 solves issues if it's Unreal.

![image](https://github.com/mbucchia/VirtualDesktop-OpenXR/assets/69611560/7abd14e6-93f1-460f-9b1c-cc76a09f6027)

No obligation for you to check, though.
