### ISSUE TITLE
Vampire The Masquerade: Justice - Compatibility

### ISSUE THREAD

**Issue by Lordubuntu94** [mbucchia/VirtualDesktop-OpenXR#34]
The following game can be added to the compatibility list:

Game: Vampire The Masquerade: Justice
Distribution: [Steam](https://store.steampowered.com/app/2431700/Vampire_The_Masquerade__Justice/?curator_clanid=4777282)
OpenXR Runtime in VD: VDXR
Runtime in overlay: VDXR

![VirtualDesktop Android-20240219-011920](https://github.com/mbucchia/VirtualDesktop-OpenXR/assets/63542392/6e038114-dcc7-4ef6-a6c8-db118a6bffa3)

The game is using UE4 and needs the parameter "-hmd=openxr" in order to use VDXR.
Like all the other openXR games that use the parameter method, hand positioning is off.
A less common problem is that the right analogue stick won't let you turn.

**Comment by mbucchia** [comment]
Thanks, For the hand positioning, is it the pivot point (twisting wrist) about 10cm off?

**Comment by Lordubuntu94** [comment]
> Thanks, For the hand positioning, is it the pivot point (twisting wrist) about 10cm off?

yes

**Comment by mbucchia** [comment]
Can you send me the log file from VDXR so I can see the application name and add a quirk for it?
