### ISSUE TITLE
Broken Edge - Compatibility

### ISSUE THREAD

**Issue by Lordubuntu94** [mbucchia/VirtualDesktop-OpenXR#35]
The following game can be added to the compatibility list:

Game: Broken Edge
Distribution: [Steam](https://store.steampowered.com/app/1947070/Broken_Edge/)
OpenXR Runtime in VD: VDXR
Runtime in overlay: VDXR

![VirtualDesktop Android-20240220-140614](https://github.com/mbucchia/VirtualDesktop-OpenXR/assets/63542392/5beaac1e-4ae0-4fc4-89b0-4943bfe09853)

The game natively supports openXR so no additional commands were used. Hand positioning and buttons worked good 👍

**Comment by mbucchia** [comment]
Thank you for the reports!
