### ISSUE TITLE
XR_EXT_hand_tracking joint positions different from SteamVR 

### ISSUE THREAD

**Issue by oneMillionWorlds** [mbucchia/VirtualDesktop-OpenXR#38]
**Describe the bug**

I'm finding that the bone poses as reported by VDXR are different from those obtained when running under SteamVR (reported using XR_EXT_hand_tracking extension).

E.g. here is the hand in XDVR 

![d2c62bcf2b7929b82f589e1b96d44f77](https://github.com/mbucchia/VirtualDesktop-OpenXR/assets/98174673/1a7aad27-aa89-44c8-9e0c-f1c6dc94876a)

![58b4a8e19b253a0fd0059a4e62906709](https://github.com/mbucchia/VirtualDesktop-OpenXR/assets/98174673/2160d4d1-00f0-4730-91e9-5d227c0436a3)

And here it is in Steam VR

![7e69106f95d68d0ce151c87cb1dbdc95](https://github.com/mbucchia/VirtualDesktop-OpenXR/assets/98174673/cdfb0ad9-99f1-49a3-b796-9e5c4f78f48e)

![6f4120e3d2803a4cc55e127364ddc6f9](https://github.com/mbucchia/VirtualDesktop-OpenXR/assets/98174673/120d4f65-4f25-4f29-a043-7ea80204d436)

It's not *that* different, but its different enough that the hands don't look right. Here they are with the bone positions rendered

VDXR:

![0f2d3778a39b9a62494971219667eade](https://github.com/mbucchia/VirtualDesktop-OpenXR/assets/98174673/cb325218-4542-4f17-ba1f-b5b5b8eb4cfc)

Stream VR:
![04f6bdeff7165f6832d3bdc81ad03957](https://github.com/mbucchia/VirtualDesktop-OpenXR/assets/98174673/f4f37117-f8da-43eb-a763-346276aaab63)

**Environment**

- _Application/Game and version_:  Tamarin Test Bed: https://github.com/oneMillionWorlds/TamarinTestBed
- _Device_: Quest 2
- _OS_: Windows 10
- _Version of Virtual Desktop_:  1.30.3 beta
- _Extension being exercised_: XR_EXT_hand_tracking

**To Reproduce**

1. Run [TamarinTestBed](https://github.com/oneMillionWorlds/TamarinTestBed)
3. Look at hands
4. See odd positioning

**Expected behaviour**

Expected that SteamVR and VDXR would produce the same bone positions

[OpenXR.log](https://github.com/mbucchia/VirtualDesktop-OpenXR/files/14593719/OpenXR.log)

**Comment by mbucchia-msft** [comment]
Not really sure what I am looking at here. SteamVR doesn't support "real hands" AFAICT, so this must be while holding a controller?

VDXR "hand joints simulation" is pretty cheap, and I don't really plan on improving it at this time. This is really meant for when a real hand is being tracked, the "hand joints simulation" code is based on Valve's own sample code [here](https://github.com/ValveSoftware/openvr/tree/master/samples/drivers/drivers/handskeletonsimulation) to provide a best-effort fallback for apps that rely on fake hand joints when holding a controller. I unfortunately don't have the time nor expertise to provide a better simulation model.

**Comment by mbucchia-msft** [comment]
The relevant code calling Valve's code is here: https://github.com/mbucchia/VirtualDesktop-OpenXR/blob/0d2a45704aa847f62d819cdbc546237b7c235ccb/virtualdesktop-openxr/hand_tracking.cpp#L305

**Comment by oneMillionWorlds** [comment]
Yes, this is while holding the controller. They aren't physically accurate (its the best guess based on touch points on the controller) but they look physically plausible from SteamVR. It's interesting that its up to the runtime to figure out the hand positions, I had always assumed (clearly incorrectly) that the device provided its option on them.

**Comment by mbucchia-msft** [comment]
There might be some simple tweaking in the code I pointed above to make it better. If you feel like experimenting.

I will try a couple of adjustments later if I find some time.

**Comment by oneMillionWorlds** [comment]
If its going to be cheap and cheerful less might be more. Tamarin itself has a hand joints simulation that it uses when XR_EXT_hand_tracking isn't available. It uses only the grip strength and uses that to open and close the hands. It's simultaneously better and worse; better in that the hands always look physically plausible, worse in that certain poses like pointing the index finger are impossible.

[Tamarin grip based bone simulation](https://github.com/oneMillionWorlds/Tamarin/blob/main/src/main/java/com/onemillionworlds/tamarin/vrhands/missinghandtracking/SyntheticBonePositions.java). It works just be having a number of recorded way points at different grip strengths and interpolating between them.

Although arguably that's going down a dead end.

No worries if its not on the roadmap though

**Comment by mbucchia** [comment]
Please note - I added support for `XR_EXT_hand_tracking_data_source` to manually activate when to retrieve simulated hand joints. This will no longer be done by default, unless the user selects "Emulate index controller".

**Comment by mbucchia** [comment]
I don't plan on making more changes to this feature.
