### ISSUE TITLE
OpenXR 게임인 pavlov VR 게임을 하고싶은데 할수가없네요;

### ISSUE THREAD

**Issue by yhe0931** [mbucchia/VirtualDesktop-OpenXR#40]
저는 pico 4를 사용하고있는 유저입니다
pavlov VR 게임이 실행을 하면 pc에서만 실행이 되고 VR 에서는 실행이 되지않습니다
버추얼 데스크탑을 사용하고있으며 VDXR 이나 Automatic 을 사용하더라도 VR화면에서만 pavlov 가 뜨지않습니다.
다른게임 잘 플레이되는데 이게임만 안되는데 이유가 있을까요?

**Comment by mbucchia** [comment]
1) what makes you think I have time to translate from your language?

2) you did not follow the instructions for filing and report, and providing the necessary information and log file.

**ANY ISSUE FILED WITHOUT THE INFORMATION REQUIRED BELOW WILL BE CLOSED WITHOUT BEING LOOKED AT. NO EXCEPTIONS.**
