### ISSUE TITLE
Possible bug in OpenXR-Vk-D3D12

### ISSUE THREAD

**Issue by gkarpa** [mbucchia/VirtualDesktop-OpenXR#43]
Sorry for hijacking this project, I wanted to open an issue in the OpenXR-Vk-D3D12 page but it seems its issues are locked. What would be the best way to communicate? Thanks.

**Comment by mbucchia** [comment]
The project isn't maintained anymore (especially with the end-of-line announcement for WMR). You can post it here, but I can't guarantee I'll do anything about it.

**Comment by gkarpa** [comment]
Thanks for the heads up. I've been working through the new OpenXR tutorial by Khronos (https://openxr-tutorial.com//windows/vulkan/index.html) using WMR with the Vk-D3D12 layer, and I'm getting a Vulkan validation error when creating the depth swapchain.

The usage flags for this swapchain are `XR_SWAPCHAIN_USAGE_SAMPLED_BIT | XR_SWAPCHAIN_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT`

but looking at the layer's code at https://github.com/mbucchia/OpenXR-Vk-D3D12/blob/27348402ec1ac0d3ac8324a7926a7941eb13bda3/XR_APILAYER_MBUCCHIA_vulkan_d3d12_interop/layer.cpp#L1987 the aspectMask is always `VK_IMAGE_ASPECT_COLOR_BIT` . 

I suppose it should conditionally be set to `VK_IMAGE_ASPECT_DEPTH_BIT` ? Or is there any other workaround I could do? Thank you again for your time!

**Comment by mbucchia-msft** [comment]
Thank you, I think you are correct regarding the bug. Have you tried building the layer with your suggested change (you can see a few lines above how to check for color/depth attachment origin)?

**Comment by gkarpa** [comment]
I just tried that and it seems to be working, that validation error is gone. 

There were also a few other validation errors (I guess irrelevant to the original issue) during the render loop:

`VUID-VkImageMemoryBarrier-oldLayout-01213(ERROR / SPEC): msgNum: 1338377618 - Validation Error: [ VUID-VkImageMemoryBarrier-oldLayout-01213 ] Object 0: handle = 0xf443490000000006, type = VK_OBJECT_TYPE_IMAGE; | MessageID = 0x4fc60592 | vkCmdPipelineBarrier(): pImageMemoryBarriers[0].newLayout (VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL) is not compatible with VkImage 0xf443490000000006[] usage flags VK_IMAGE_USAGE_SAMPLED_BIT|VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT. The Vulkan spec states: If srcQueueFamilyIndex and dstQueueFamilyIndex define a queue family ownership transfer or oldLayout and newLayout define an image layout transition, and oldLayout or newLayout is VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL then image must have been created with VK_IMAGE_USAGE_TRANSFER_DST_BIT (https://vulkan.lunarg.com/doc/view/1.3.275.0/windows/1.3-extensions/vkspec.html#VUID-VkImageMemoryBarrier-oldLayout-01213)`

Also `VUID-vkCmdClearColorImage-image-00002` and `VUID-vkCmdClearDepthStencilImage-pRanges-02660` but the error cause was the same as above.

I "fixed" all those too but from the application side, by appending the `XR_SWAPCHAIN_USAGE_TRANSFER_DST_BIT` flag in the `usageFlags` of all the created swapchains. I don't know however if this is absolutely correct nor how to fix them at the layer code (if possible) without having to set that flag.

**Comment by gkarpa** [comment]
Actually I just noticed that the `VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL` layout isn't used anywhere in the layer, so let's forget about the rest. They're possible bugs in the tutorial code. Sorry about that.

**Comment by gkarpa** [comment]
What confuses me a little is that depending on the runtime I use, I get different validation errors during the render loop (again, regardless of the aspectMask issue in the Vk-D3D12 layer). 

For example when I'm using WMR & Vk-D3D12 I get the errors that I mentioned above. But when I'm using the Meta XR simulator (https://developer.oculus.com/documentation/native/xrsim-native) which doesn't seem to need the Vk-D3D12, then I'm also getting this:
`UNASSIGNED-CoreValidation-DrawState-InvalidImageLayout(ERROR / SPEC): msgNum: 1303270965 - Validation Error: [ UNASSIGNED-CoreValidation-DrawState-InvalidImageLayout ] Object 0: handle = 0x1da433c30b0, type = VK_OBJECT_TYPE_COMMAND_BUFFER; Object 1: handle = 0x7f79ad0000000050, type = VK_OBJECT_TYPE_IMAGE; | MessageID = 0x4dae5635 | vkQueueSubmit(): pSubmits[0].pCommandBuffers[0] command buffer VkCommandBuffer 0x1da433c30b0[] expects VkImage 0x7f79ad0000000050[] (subresource: aspectMask 0x2 array layer 0, mip level 0) to be in layout VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL--instead, current layout is VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL.
    Objects: 2
        [0] 0x1da433c30b0, type: 6, name: NULL
        [1] 0x7f79ad0000000050, type: 10, name: NULL`

I guess the two runtimes implement something differently. Anyway, still a lot to learn :) Thanks again for your time & feedback.

**Comment by mbucchia-msft** [comment]
I looked closer at Chapter 3, and I believe you've found a legitimate bug with the missing `XR_SWAPCHAIN_USAGE_TRANSFER_DST_BIT`. I've reported it to the workgroup managing the OpenXR Tutorials.

**Comment by mbucchia** [comment]
FWIW I have fixed the aspect bit bug in VDXR (same code as OpenXR-Vk-D3D12): f18a9617714eb799895449818a4ec0e9e60c94ff

Whether I'll make a release of OpenXR-Vk-D3D12 though is unknown. I don't have a code signing certificate at the moment.

**Comment by gkarpa** [comment]
Since I use it only for my development purposes I'm perfectly fine with having it fixed locally, so not a problem by any means! Thank you.

**Comment by mbucchia** [comment]
I committed the change to OpenXR-Vk-D3D12 for prosperity, but won't be making a release.

https://github.com/mbucchia/OpenXR-Vk-D3D12/commit/6fe0722b52a43e38899920440e9d86f3d5949145

Closing.
