### ISSUE TITLE
Feature request: Add floor fix/calibration

### ISSUE THREAD

**Issue by FractalEngineer** [mbucchia/VirtualDesktop-OpenXR#44]
**Describe the issue**

Some apps like Pavlov do not have the option to calibrate height/floor
On the other hand, all other runtimes (Oculus, SteamVR) have a tool to perform floor calibration (either by placing the controller or headset on the ground)

As a result, it appears that when using Pavlov in VDXR, the floor height defaults to too low, making it impossible to crouch and pick stuff up the floor

**Environment**

Win11
MQ3 V64
Pavlov update30
VD 1.30.5

**To Reproduce**

Launch game in VDXR runtime

**Expected behavior**

Quest VD app has some way to fix floor from the menu

VDXR has been a gamechanger in all my other apps with significantly improved performance; having to switch back to SteamVR for this reason would be such a downgrade 😅

**Comment by mbucchia** [comment]
Dup of #18
