### ISSUE TITLE
Fov tangent multiplier

### ISSUE THREAD

**Issue by mykimy** [mbucchia/VirtualDesktop-OpenXR#45]
Hello,

I'm using Virtual Desktop/VDXR with Dirt Rally 2 and I'm using the hiddenMeshVerticalScale OpenComposite setting. Doing this improves performance significantly.

I tried to do this with Automobilista 2 but couldn't get it to work. I even tried OpenXR Toolkit with the FOV setting, but it distorts the image too much. Currently, I'm stuck with Meta Link for this game because of this issue.

When playing simracing games, it is great to reduce the vertical FOV, not only for performance but also because it is more immersive, like wearing a helmet.

Is there a way to do this with Virtual Desktop/VDXR? If not, is there any chance this feature could be implemented in the future?

**Comment by mbucchia** [comment]
I offer no support for any apps running OpenComposite.

**Comment by mykimy** [comment]
I @mbucchia 
My question is not specific to 0pencomposite, iRacing or WRC both use OpenXR runtime and I cannot set vertical FOV tangent multiplier when using Virtual Desktop/VDXR.
