### ISSUE TITLE
Runtime reverts to "Oculus" when OpenXR Toolkit is enabled with VDXR

### ISSUE THREAD

**Issue by Conmiro** [mbucchia/VirtualDesktop-OpenXR#8]
**Describe the bug**

When enabling VR mode in MSFS while having OpenXR Toolkit enabled and the new VDXR runtime enabled in Virtual Desktop streamer desktop app, the performance overlay shows that Oculus is the active runtime (instead of VDXR as expected). I narrowed the issue down by disabling/enabling things individually, and I consistently get Oculus displaying (and can't use OpenXR capabilities) unless I turn off OpenXR Toolkit. Alternatively, I can set the runtime back to SteamVR in the streamer application and I'm able to use the OpenXR toolkit.

I'm not sure if this impacts other supported VDXR games, or if it's unique to MSFS.

[OpenXR.log](https://github.com/mbucchia/VirtualDesktop-OpenXR/files/13110534/OpenXR.log)

**Environment**

- _Application/Game and version_:  MSFS 1.34.16.0
- _Version of Virtual Desktop_:  1.29.3 (Beta)

Quest Pro Headset

**To Reproduce**

_Steps to reproduce the behavior:_

1. Select VDXR as the Runtime in the beta version of the streamer app.
2. Enable OpenXR Toolkit
3. Launch Virtual Desktop in Quest Pro
4. Launch SteamVR
5. Launch Microsoft Flight Simulator
6. Switch to VR Mode
7. Activate performance overlay
8. Runtime shown as "Oculus" and cannot use OpenXR Toolkit hotkeys (Ctrl+F2) nor see toolkit overlay.

**Expected behavior**

I expected to see the runtime as VDXR. I can get the expected behavior by disabling OpenXR Toolkit. If I switch back to SteamVR runtime, I can use OpenXR toolkit fine.

**Comment by mbucchia** [comment]
Seeing "Oculus" in MSFS is a known issue. It still means VDXR is used (because MSFS doesn't have Oculus mode support). It's a simple cosmetic bug that is already fixed in the next version.

**Comment by Conmiro** [comment]
@mbucchia I thought it was a UI bug at first, but I can't utilize any of the OpenXR capabilities. I can't see the OpenXR overlay in-game.

**Comment by mbucchia** [comment]
Not seeing the menu is another issue that is already fixed for the next version. Meanwhile you can go to MSFS VR settings and set Reprojection Mode to None. The other options don't do anything with MSFS.

**Comment by Conmiro** [comment]
@mbucchia Ah okay, thanks. 

"The other options don't do anything with MSFS." OpenXR Toolkit says foveated rendering is supported for Quest Pro and MSFS. I know historically this was only possible over Air Link. Does VDXR not enable this with Virtual Desktop and OpenXR Toolkit?

**Comment by mbucchia** [comment]
I meant "the other [Reprojection Mode] options [Depth, Motion] don't do anything".
The OpenXR Toolkit options (such as foveated rendering) will work fine. For eye tracking on Pro, you must make sure to enable "Forward eye/face data to the PC" in Virtual desktop settings.

**Comment by Conmiro** [comment]
Awesome great. I do have the "forward eye/face data to the PC" option enabled. I look forward to the next version which fixes the toolkit overlay issue so I can take advantage of the eye tracking for FR. 

Appreciate the prompt responses and insights!

**Comment by mbucchia** [comment]
Have you tried setting Reprojection Mode to None in MSFS? It should fix your issue.

**Comment by Conmiro** [comment]
I thought I had it off already, but apparently it was set to Depth! Yes, setting Reprojection Mode to Off caused the toolkit overlay to show up. Many thanks!!
