### ISSUE TITLE
Streamer 1.29.3 hotspot wifi  issue

### ISSUE THREAD

**Issue by Astrodoc76** [mbucchia/VirtualDesktop-OpenXR#9]
**ANY ISSUE FILED WITHOUT THE INFORMATION REQUIRED BELOW WILL BE CLOSED WITHOUT BEING LOOKED AT. NO EXCEPTIONS.**

**Describe the bug**
I play fs 2020 using vd conncting my quest 3 with hotspot wifi on a D-link 1850 usb Wi-Fi 6 AX1800 adapter

with the new vd streamer 1.29.3 
In fs 2020 switching to vr causes to quit the game
if i connect quest 3 to the  wifi router (wifi 5 only)  and not on the hotspot (cable connected to pc) all works fine 

with the old streamer 1.29.0 my quest connected via hotspot and vd works fine

i noted in streamer app activating hotspot wifi  the ethernet status changes from YES to NO

the streamer 1.29.0 switching on the hotspot the ethernet status stay in YES

_A clear and concise description of what the bug is._
_Always attach (upload, do not copy/paste) the `OpenXT.log` file that can be found at `%ProgramData%\Virtual Desktop`_

**Environment**

- _Application/Game and version_:  fs 2020
- _Version of Virtual Desktop_:  

**To Reproduce**

_Steps to reproduce the behavior:_

1. Run '....' game connected vd using hotspot 
2. Enable option '....'VR
3. See error

**Expected behavior** 
game quit 

_A clear and concise description of what you expected to happen._
[StreamerLog.txt](https://github.com/mbucchia/VirtualDesktop-OpenXR/files/13170742/StreamerLog.txt)
![wifi hotspot on](https://github.com/mbucchia/VirtualDesktop-OpenXR/assets/149017629/751ae9d4-756e-4ac5-8c6a-23b528665a29)
![wi-fi htspot off](https://github.com/mbucchia/VirtualDesktop-OpenXR/assets/149017629/78450fee-4cf6-4c8a-a090-708d2090c317)
[OpenXR.log](https://github.com/mbucchia/VirtualDesktop-OpenXR/files/13170789/OpenXR.log)

**Comment by mbucchia** [comment]
This doesn't sound like it had anything to do with VDXR. The concept of Hotspot or Wi-Fi router are invisible to VDXR.

Try the Virtual Desktop Discord instead.
